CREATE TYPE anchor_status_enum AS ENUM ('PENDING','CONFIRMED','PENDING_GAS','FAILED');
CREATE TYPE gender_enum AS ENUM ('MALE','FEMALE');
CREATE TYPE prediction_status_enum AS ENUM ('PENDING','COMPLETED','FAILED');
CREATE TYPE stunt_status_enum AS ENUM ('NORMAL','AT_RISK','STUNTED','SEVERELY_STUNTED');
CREATE TYPE role_enum AS ENUM ('PARENT','MEDIC','POSYANDU','ADMIN');
CREATE TYPE vc_type_enum AS ENUM ('IMMUNIZATION_COMPLETE','NUTRITION_STATUS','GROWTH_MILESTONE');
